# Set the workflow name to GitHub Actions Demo
name: GitHub Actions Demo

# Add the triggers to the worklow with the help of Ctrl+Space and the documentation. We want the workflow to trigger:
# on every push to the main branch, but not when there are changes to files in the .github folder.
# on every pull request with main as the base branch
# Every sunday at 6:15 UTC
# Manually

on:
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

# Create a job Build that runs on the latest Ubuntu image on GitHub hosted runners. Check the documentation of the virtual environments what label to use and what version it is. The job should do the following things:
# Output the name of the event that triggered the workflow
# Output the name of the branch that the repository is currently referencing
# List all files in the repository

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "🎉 The job was triggered by event: ${{ github.event_name }}"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ."

      - uses: actions/checkout@v3.3.0

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree

