# Set the workflow name to GitHub Actions Demo
name: GitHub Actions Demo

# Add the triggers to the worklow with the help of Ctrl+Space and the documentation. We want the workflow to trigger:
# on every push to the main branch, but not when there are changes to files in the .github folder.
# on every pull request with main as the base branch
# Every sunday at 6:15 UTC
# Manually

on:
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  # Adding a input for picking environments to manual workflow trigger
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true

# Create a job Build that runs on the latest Ubuntu image on GitHub hosted runners. Check the documentation of the virtual environments what label to use and what version it is. The job should do the following things:
# Output the name of the event that triggered the workflow
# Output the name of the branch that the repository is currently referencing
# List all files in the repository

# Test: runs on ubuntu-latest after Build. Only runs when the workflow was triggered manually. 
#       Runs on the environment Test. The job writes Testing... to the workflow log.
# Load-Test: runs on ubuntu-latest after Build. Only runs when the workflow was triggered manually. 
# Runs on the environment Load-Test. The job writes Testing... to the workflow log and sleeps for 15 seconds.
# Production: runs on ubuntu-latest after Test and Load-Test. Deploys to the environment Production onyl if this was selected as the input parameter. 
#             The environment has the URL https://writeabout.net. To simulate deployment, the job will execute 5 steps. 
#             Each step with writes Step x deploying... to the workflow log and sleeps for 10 seconds.

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "🎉 The job was triggered by event: ${{ github.event_name }}"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ."

      - uses: actions/checkout@v3.3.0

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree

  Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Test
    steps:
      - run: echo "🧪 Testing..."

  Load-Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Load-Test
    steps:
      - run: |
          echo "🧪 Testing..."
          sleep 15

  Production:
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    environment:
      name: Production
      url: https://writeabout.net
    if: github.event.inputs.environment == 'Production'
    steps:
      - run: |
          echo "🚀 Step 1..."
          sleep 10
      - run: |
          echo "🚀 Step 2..."
          sleep 10
      - run: |
          echo "🚀 Step 3..."
          sleep 10
      - run: |
          echo "🚀 Step 4..."
          sleep 10
      - run: |
          echo "🚀 Step 5..."
          sleep 10

# when commit changes to ignore pipeline to run, write [skip ci]

