# Set the name to Reuse other workflow and add a manual trigger.
name: Reuse other workflow

on: [workflow_dispatch]

# Add a job call-workflow that uses the reusable workflow and passes in your user name as an input parameter.
jobs:
  call-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      who-to-greet: '@octocat'
  use-output:
    runs-on: ubuntu-latest
    needs: [call-workflow]
    steps:
      - run: echo "Time was ${{ needs.call-workflow.outputs.current-time }}"
